###
# 2.1. Создание нового предложения.
POST http://localhost:3000/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFuZHJlaS5mZXJAYXQudXJmdS5ydSIsIm5hbWUiOiJBbmRyZXcgRmVyIiwiaWQiOiI2NjQ2M2Q4NWU4MWNhMzI0MmQ1ZTVhYzEiLCJpYXQiOjE3MTY0NzgzNTYsImV4cCI6MTcxNjY1MTE1Nn0.R_XD-vPV_Q8cO2V7Ko4151Akbp7ReSrSXCy5YVgEZ6w

{
  "title": "Offer by authorized user",
  "description": "Description of offer",
  "postDate": "2024-05-16T21:57:00",
  "city": "Paris",
  "preview": "image1.png",
  "pictures": ["image1.png", "image2.png", "image3.png"],
  "isPremium": false,
  "isFavorite": true,
  "rating": 4,
  "housingType": "Apartment",
  "roomsCount": 3,
  "guestsCount": 4,
  "price": 5000,
  "facilities": ["Breakfast", "Air conditioning"],
  "authorId": "66463d85e81ca3242d5e5ac1",
  "coordinates": {
    "latitude": 48.85661,
    "longitude": 2.351499
  }
}

###
# 2.2. Редактирование предложения.
PATCH http://localhost:3000/offers/6648d07fb176c942f829c26f HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFuZHJlaS5mZXJAYXQudXJmdS5ydSIsIm5hbWUiOiJBbmRyZXcgRmVyIiwiaWQiOiI2NjQ2M2Q4NWU4MWNhMzI0MmQ1ZTVhYzEiLCJpYXQiOjE3MTY0NzgzNTYsImV4cCI6MTcxNjY1MTE1Nn0.R_XD-vPV_Q8cO2V7Ko4151Akbp7ReSrSXCy5YVgEZ6w

{
  "title": "Second offer",
  "description": "Description of second offer",
  "postDate": "2024-05-16T22:57:00",
  "city": "Paris",
  "preview": "image1.png",
  "pictures": ["image4.png", "image5.png", "image6.png"],
  "isPremium": false,
  "isFavorite": false,
  "rating": 4,
  "housingType": "Apartment",
  "roomsCount": 3,
  "guestsCount": 4,
  "price": 5000,
  "facilities": ["Breakfast", "Air conditioning"],
  "authorId": "66463d85e81ca3242d5e5ac1",
  "coordinates": {
    "latitude": 48.85661,
    "longitude": 2.351499
  }
}

###
# 2.3. Удаление предложения.
DELETE http://localhost:3000/offers/6648d07fb176c942f829c26f HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFuZHJlaS5mZXJAYXQudXJmdS5ydSIsIm5hbWUiOiJBbmRyZXcgRmVyIiwiaWQiOiI2NjQ2M2Q4NWU4MWNhMzI0MmQ1ZTVhYzEiLCJpYXQiOjE3MTY0NzgzNTYsImV4cCI6MTcxNjY1MTE1Nn0.R_XD-vPV_Q8cO2V7Ko4151Akbp7ReSrSXCy5YVgEZ6w

###
# 2.4. Получение списка предложений по аренде.
GET http://localhost:3000/offers HTTP/1.1

###
# 2.5. Получение детальной информации о предложении.
GET http://localhost:3000/offers/6648d07fb176c942f829c26f HTTP/1.1

###
# 2.6. Получение списка комментариев для предложения.
GET http://localhost:3000/offers/6648d3bd48bb9528da7cf3b3/comments HTTP/1.1

###
# 2.7. Добавление комментария для предложения.
POST http://localhost:3000/offers/6648d3bd48bb9528da7cf3b3/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFuZHJlaS5mZXJAYXQudXJmdS5ydSIsIm5hbWUiOiJBbmRyZXcgRmVyIiwiaWQiOiI2NjQ2M2Q4NWU4MWNhMzI0MmQ1ZTVhYzEiLCJpYXQiOjE3MTY0NzgzNTYsImV4cCI6MTcxNjY1MTE1Nn0.R_XD-vPV_Q8cO2V7Ko4151Akbp7ReSrSXCy5YVgEZ6w

{
  "text": "Comment by authorized user",
  "postDate": "2024-05-16T22:57:00",
  "offerId": "6648d3bd48bb9528da7cf3b3",
  "userId": "66463d85e81ca3242d5e5ac1"
}

###
# 2.8. Создание нового пользователя.
POST http://localhost:3000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Andrew Fer",
  "email": "andrei.fer@at.urfu.ru",
  "password": "Zaq1Xsw2",
  "avatar": "avatar.png",
  "userType": "Common"
}

###
# 2.9. Вход в закрытую часть приложения.
POST http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "andrei.fer@at.urfu.ru",
  "password": "Zaq1Xsw2"
}

###
# 2.10. Выход из закрытой части приложения.
DELETE http://localhost:3000/users/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFuZHJlaS5mZXJAYXQudXJmdS5ydSIsIm5hbWUiOiJBbmRyZXcgRmVyIiwiaWQiOiI2NjQ2M2Q4NWU4MWNhMzI0MmQ1ZTVhYzEiLCJpYXQiOjE3MTY0NzgzNTYsImV4cCI6MTcxNjY1MTE1Nn0.R_XD-vPV_Q8cO2V7Ko4151Akbp7ReSrSXCy5YVgEZ6w

###
# 2.11. Проверка состояния пользователя.
GET http://localhost:3000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFuZHJlaS5mZXJAYXQudXJmdS5ydSIsIm5hbWUiOiJBbmRyZXcgRmVyIiwiaWQiOiI2NjQ2M2Q4NWU4MWNhMzI0MmQ1ZTVhYzEiLCJpYXQiOjE3MTY0NzgzNTYsImV4cCI6MTcxNjY1MTE1Nn0.R_XD-vPV_Q8cO2V7Ko4151Akbp7ReSrSXCy5YVgEZ6w

###
# 2.12. Получение списка премиальных предложений для города.
GET http://localhost:3000/offers/premium?city=Paris HTTP/1.1

###
# 2.12. Получение списка премиальных предложений для города.
GET http://localhost:3000/offers/premium?city=Brussels HTTP/1.1

###
# 2.13. Получения списка предложений, добавленных в избранное.
GET http://localhost:3000/offers/favorites HTTP/1.1

###
# 2.14. Добавление предложения в избранное.
POST http://localhost:3000/offers/favorites/6648d3bd48bb9528da7cf3b3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFuZHJlaS5mZXJAYXQudXJmdS5ydSIsIm5hbWUiOiJBbmRyZXcgRmVyIiwiaWQiOiI2NjQ2M2Q4NWU4MWNhMzI0MmQ1ZTVhYzEiLCJpYXQiOjE3MTY0NzgzNTYsImV4cCI6MTcxNjY1MTE1Nn0.R_XD-vPV_Q8cO2V7Ko4151Akbp7ReSrSXCy5YVgEZ6w

###
# 2.14. Удаление предложения из избранного.
DELETE http://localhost:3000/offers/favorites/6648d3bd48bb9528da7cf3b3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFuZHJlaS5mZXJAYXQudXJmdS5ydSIsIm5hbWUiOiJBbmRyZXcgRmVyIiwiaWQiOiI2NjQ2M2Q4NWU4MWNhMzI0MmQ1ZTVhYzEiLCJpYXQiOjE3MTY0NzgzNTYsImV4cCI6MTcxNjY1MTE1Nn0.R_XD-vPV_Q8cO2V7Ko4151Akbp7ReSrSXCy5YVgEZ6w

###

GET http://localhost:3000/upload/readme.txt HTTP/1.1

###

POST http://localhost:3000/users/66463d85e81ca3242d5e5ac1/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=w

--w
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< /Users/Andrew/Pictures/123.png
--w--
