POST http://localhost:3000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Andrew Fer",
  "email": "andrei.fer@at.urfu.ru",
  "password": "Zaq1Xsw2",
  "avatar": "avatar.png",
  "userType": "Common"
}

###

GET http://localhost:3000/users/login HTTP/1.1

###

POST http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "andrei.fer@at.urfu.ru",
  "password": "Zaq1Xsw2"
}

###

DELETE http://localhost:3000/users/logout HTTP/1.1

###

GET http://localhost:3000/offers HTTP/1.1

###

POST http://localhost:3000/offers HTTP/1.1
Content-Type: application/json

{
  "title": "First offer",
  "description": "Description of first offer",
  "postDate": "2024-05-16T21:57:00",
  "city": "Paris",
  "preview": "image1.png",
  "pictures": ["image1.png", "image2.png", "image3.png"],
  "isPremium": false,
  "isFavorite": false,
  "rating": 4,
  "housingType": "Apartment",
  "roomsCount": 3,
  "guestsCount": 4,
  "price": 5000,
  "facilities": ["Breakfast", "Air conditioning"],
  "authorId": "66463d85e81ca3242d5e5ac1",
  "coordinates": {
    "latitude": 48.85661,
    "longitude": 2.351499
  }
}

###

GET http://localhost:3000/offers/66464988397eadfaa039e62e HTTP/1.1

###

DELETE http://localhost:3000/offers/66464988397eadfaa039e62e HTTP/1.1

###

PATCH http://localhost:3000/offers/66464988397eadfaa039e62e HTTP/1.1
Content-Type: application/json

{
  "title": "Second offer",
  "description": "Description of second offer",
  "postDate": "2024-05-16T22:57:00",
  "city": "Paris",
  "preview": "image1.png",
  "pictures": ["image4.png", "image5.png", "image6.png"],
  "isPremium": false,
  "isFavorite": false,
  "rating": 4,
  "housingType": "Apartment",
  "roomsCount": 3,
  "guestsCount": 4,
  "price": 5000,
  "facilities": ["Breakfast", "Air conditioning"],
  "authorId": "66463d85e81ca3242d5e5ac1",
  "coordinates": {
    "latitude": 48.85661,
    "longitude": 2.351499
  }
}

###

GET http://localhost:3000/offers/66464988397eadfaa039e62e/comments HTTP/1.1

###

POST http://localhost:3000/offers/66464988397eadfaa039e62e/comments HTTP/1.1
Content-Type: application/json

{
  "text": "Text for comment"
}

###

GET http://localhost:3000/offers/premium?city=Paris HTTP/1.1

###

GET http://localhost:3000/offers/premium?city=Brussels HTTP/1.1

###

GET http://localhost:3000/offers/favorites HTTP/1.1

###

POST http://localhost:3000/offers/favorites/66464988397eadfaa039e62e HTTP/1.1

###

DELETE http://localhost:3000/offers/favorites/66464988397eadfaa039e62e HTTP/1.1