openapi: 3.1.0
info:
  title: "Six-cities API (Проект 'Шесть городов')"
  version: "1.0.0"
  contact:
    name: Andrew Fer
    email: andrei.fer@urfu.me
tags:
  - name: offers
    description: Действия с предложениями
  - name: users
    description: Действия с пользователями
  - name: comments
    description: Действия с комментариями
paths:
  /users/register:
    post:
      tags:
        - users
      summary: Регистрация пользователя
      description: Регистрирует нового пользователя

  /users/login:
    post:
      tags:
        - users
      summary: Авторизует пользователя
      description: Авторизует пользователя по логину и паролю
    
    get:
      tags:
        - users
      summary: Проверка состояния пользователя
      description: Возвращает информацию по авторизованному пользователю

  /users/{userId}/avatar:
    post:
      tags:
        - users
      summary: Загрузить изображение аватара
      description: Загружает изображение аватара пользователя. Изображение
        аватара должно быть в формате `png` или `jpg`.